services:
  postgis:
    image: postgis/postgis:15-3.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword 
    ports:
      - 5432:5432
    volumes:
      - db:/data/db
  geoserver:
    image: docker.osgeo.org/geoserver:2.23.0
    depends_on:
      - postgis
    environment:
      - CORS_ENABLED=true
      - CORS_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,HEAD,OPTIONS
      - CORS_ALLOWED_HEADERS=*
    ports:
      - 5050:8080
    volumes:
      - ./data/:/opt/geoserver_data/data
volumes:
  db:
